theme = "ananke"

baseURL = "https://luofugui.github.io/crescent-ccms.io/"
languageCode = "en-us"
title = "Crescent Chinese Music Studio"

[params]
  site_logo = "img/logo.png"
  custom_css = ["css/custom.css"]
  # Show recent posts section on homepage; use 'performances' as the main section
  mainSections = ["performances"]

  [params.ananke]
    show_recent_posts = true

  [params.ananke.home]
    content_alignment = "center"

  [params.ananke.social]
    icon_path = "ananke/socials/%s.svg"

  [params.ananke.social.follow]
    new_window_icon = false
    networks = ["facebook", "instagram", "youtube"]

  [params.ananke.social.share]
    icons = true
    sharetext = true
    networks = ["facebook", "twitter", "email"]

[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    identifier = "about"
    url  = "/about/"
    weight = 2
  [[menu.main]]
    name = "Gallery"
    url  = "/gallery/"
    weight = 3
  [[menu.main]]
    name = "Videos"
    url  = "/videos/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 6
  [[menu.main]]
    name = "Performances"
    url = "/performances/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
